version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_desafio
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goexpert
      MYSQL_PASSWORD: root
    ports:
    # aqui estou dizendo que a porta 3306 do meu pc está conectando com a porta 3306 do container
      - 3306:3306